version: '3.3'

services:
  bot:
    image: python:3.9
    container_name: ${PROJECT_NAME}-bot
    build:
      dockerfile: Dockerfile.bot
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
      - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: python3 src/bot.py
    restart: always
    depends_on:
      - db
      - redis
      - web
    env_file: .env

  web:
    image: python:3.9
    container_name: ${PROJECT_NAME}-web
    build:
      dockerfile: Dockerfile.web
      context: .
    working_dir: "/usr/src/app/${PROJECT_NAME:-web}"
    volumes:
      - .:/usr/src/app/${PROJECT_NAME:-web}
    command: python3 src/manage.py runserver
    ports:
      - 8050:8000
    restart: always
    depends_on:
      - db
      - redis
    env_file: .env

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    container_name: ${PROJECT_NAME}-db
    env_file: .env
    ports:
      - 5433:5432

  redis:
    image: redis:6.2-alpine
    container_name: ${PROJECT_NAME}-redis
    restart: always
    ports:
      - 6380:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
